exp_name: '' #'DaconBaseV1Fold0'
train_data: dataset/dataset.csv
test_data: dataset/test_dataset.csv
manualSeed: 1234

# learning parameters
workers: 4
batch_size: 32
num_iter: 2 # in general, it means total batch size. but if valInterval <= 0, it means total epoch
valInterval: -1
saved_model: saved_models/DaconBaseV1Fold0/best_f1.pth
FT: false

adam: false
lr: 0.01
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5

start_iter: 0

# transform parameters
imgH: 256
imgW: 256

# model parameters
model_name: efficientnet_b0
feature_dim: 1000
num_classes: 19

# train parameters
verbose: -1

# kfold: 
kfold: 0
n_splits: 5

#result
output: "submission"